uv run --active -m cs336_alignment.grpo.run_grpo \
  --model_path models/bf16/models--Qwen--Qwen2.5-Math-1.5B/snapshots/4a83ca6e4526a4f2da3aa259ec36c259f66b2ab2/ \
  --data_train_path data/MATH/train.jsonl \
  --data_eval_path data/MATH/validation.jsonl \
  --prompt r1_zero \
  --train_device cuda:0 \
  --eval_device cuda:0 \
  --checkpoint_dir outputs/ckpt/grpo/ \
  --log_dir outputs/logs/grpo/ \
  --lr_scheduler cosine_with_min_lr \
  --lr 0.00004 \
  --n_grpo_steps 200 \
  --n_train_steps_per_rollout_batch 4 \
  --cliprange 0.2 \
  --train_batch_size 16 \
  --gradient_accumulation_steps 16 \
  --rollout_batch_size 8 \
  --group_size 4 \
  --loss_type reinforce_with_baseline \
  --gpu_memory_utilization 0.275 \
  --do_eval \
  --eval_every 10 \
  --eval_batch_size 2
  # --normalize_by_std